#!/usr/bin/env bash
set -euo pipefail

prefix="${PREFIX:-$HOME/.local}"
bin_dir="$prefix/bin"
codex_home="${CODEX_HOME:-$HOME/.codex}"
codex_skills_dir="$codex_home/skills"
yes=0
dry_run=0

usage() {
  cat <<'USAGE'
Usage: ./uninstall.sh [--yes] [--dry-run]

Removes only claude-to-codex-owned artifacts:
  - claude-to-codex, codex-with-claude, and cwc from PREFIX/bin
  - Codex skill wrappers generated by claude-to-codex
  - the Codex MCP entry named claude-bridge, only if it points at claude-to-codex

It does not remove unrelated Codex config, Codex auth, hand-written Codex
skills, agents, plugins, or Claude Code configuration.
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --yes|-y)
      yes=1
      ;;
    --dry-run|-n)
      dry_run=1
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      printf 'uninstall.sh: unknown argument: %s\n\n' "$1" >&2
      usage >&2
      exit 2
      ;;
  esac
  shift
done

run() {
  if [[ "$dry_run" -eq 1 ]]; then
    printf 'would run:'
    printf ' %q' "$@"
    printf '\n'
    return 0
  fi
  "$@"
}

if [[ "$yes" -ne 1 && "$dry_run" -ne 1 ]]; then
  printf 'This will remove claude-to-codex-owned files only. Continue? [y/N] '
  read -r answer
  case "$answer" in
    y|Y|yes|YES) ;;
    *)
      printf 'uninstall.sh: cancelled\n'
      exit 1
      ;;
  esac
fi

printf 'Removing installed claude-to-codex commands from %s\n' "$bin_dir"
run rm -f \
  "$bin_dir/claude-to-codex" \
  "$bin_dir/codex-with-claude" \
  "$bin_dir/cwc"

if [[ -d "$codex_skills_dir" ]]; then
  printf 'Removing generated Codex skill wrappers from %s\n' "$codex_skills_dir"
  while IFS= read -r -d '' skill_file; do
    if grep -q 'generated-by: claude-to-codex sync-' "$skill_file"; then
      skill_dir="$(dirname "$skill_file")"
      run rm -f "$skill_file"
      run rmdir "$skill_dir" 2>/dev/null || true
    fi
  done < <(find "$codex_skills_dir" -mindepth 2 -maxdepth 2 -type f -name 'SKILL.md' -print0)
fi

if command -v codex >/dev/null 2>&1; then
  if codex mcp get claude-bridge >/tmp/claude-to-codex-mcp-get.$$ 2>/dev/null; then
    if grep -q 'claude-to-codex' /tmp/claude-to-codex-mcp-get.$$; then
      if [[ "$dry_run" -eq 1 ]]; then
        printf 'Would remove Codex MCP entry claude-bridge\n'
      else
        printf 'Removing Codex MCP entry claude-bridge\n'
      fi
      run codex mcp remove claude-bridge
    else
      printf 'Leaving Codex MCP entry claude-bridge because it does not appear to point at claude-to-codex\n'
    fi
  fi
  rm -f /tmp/claude-to-codex-mcp-get.$$
else
  printf 'Codex CLI not found; leaving any Codex MCP config untouched\n'
fi

if [[ "$dry_run" -eq 1 ]]; then
  printf 'Dry run complete. No files were removed.\n'
else
  printf 'Uninstall complete. Claude Code configuration was not changed.\n'
fi
