#!/usr/bin/env bash
set -euo pipefail

prefix="${PREFIX:-$HOME/.local}"
bin_dir="$prefix/bin"
codex_home="${CODEX_HOME:-$HOME/.codex}"
codex_skills_dir="$codex_home/skills"
codex_agents_dir="$codex_home/agents"
project_root="${CLAUDE_BRIDGE_PROJECT_ROOT:-}"
yes=0
dry_run=0
mcp_get_file=""

usage() {
  cat <<'USAGE'
Usage: ./uninstall.sh [--yes] [--dry-run]

Removes only claude-to-codex-owned artifacts:
  - claude-to-codex, codex-with-claude, and cwc from PREFIX/bin
  - Codex skill wrappers generated by claude-to-codex
  - Codex agents generated by claude-to-codex
  - the Codex MCP entry named claude-bridge, only if it points at claude-to-codex

It does not remove unrelated Codex config, Codex auth, hand-written Codex
skills, agents, plugins, or Claude Code configuration.
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --yes|-y)
      yes=1
      ;;
    --dry-run|-n)
      dry_run=1
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      printf 'uninstall.sh: unknown argument: %s\n\n' "$1" >&2
      usage >&2
      exit 2
      ;;
  esac
  shift
done

run() {
  if [[ "$dry_run" -eq 1 ]]; then
    printf 'would run:'
    printf ' %q' "$@"
    printf '\n'
    return 0
  fi
  "$@"
}

cleanup() {
  if [[ -n "$mcp_get_file" ]]; then
    rm -f "$mcp_get_file"
  fi
}
trap cleanup EXIT

find_root() {
  local dir="$PWD"
  while true; do
    if [[ -e "$dir/.mcp.json" || -e "$dir/CLAUDE.md" || -d "$dir/.git" ]]; then
      printf '%s\n' "$dir"
      return 0
    fi
    local parent
    parent="$(dirname "$dir")"
    if [[ "$parent" == "$dir" ]]; then
      printf '%s\n' "$PWD"
      return 0
    fi
    dir="$parent"
  done
}

remove_generated_agents() {
  local agents_dir="$1"
  if [[ -d "$agents_dir" ]]; then
    printf 'Removing generated Codex agents from %s\n' "$agents_dir"
    while IFS= read -r -d '' agent_file; do
      if grep -q 'generated-by: claude-to-codex sync-agents' "$agent_file"; then
        run rm -f "$agent_file"
      fi
    done < <(find "$agents_dir" -mindepth 1 -maxdepth 1 -type f -name '*.toml' -print0)
  fi
}

if [[ "$yes" -ne 1 && "$dry_run" -ne 1 ]]; then
  printf 'This will remove claude-to-codex-owned files only. Continue? [y/N] '
  read -r answer
  case "$answer" in
    y|Y|yes|YES) ;;
    *)
      printf 'uninstall.sh: cancelled\n'
      exit 1
      ;;
  esac
fi

printf 'Removing installed claude-to-codex commands from %s\n' "$bin_dir"
run rm -f \
  "$bin_dir/claude-to-codex" \
  "$bin_dir/codex-with-claude" \
  "$bin_dir/cwc"

if [[ -d "$codex_skills_dir" ]]; then
  printf 'Removing generated Codex skill wrappers from %s\n' "$codex_skills_dir"
  while IFS= read -r -d '' skill_file; do
    if grep -q 'generated-by: claude-to-codex sync-' "$skill_file"; then
      skill_dir="$(dirname "$skill_file")"
      run rm -f "$skill_file"
      run rmdir "$skill_dir" 2>/dev/null || true
    fi
  done < <(find "$codex_skills_dir" -mindepth 2 -maxdepth 2 -type f -name 'SKILL.md' -print0)
fi

remove_generated_agents "$codex_agents_dir"
if [[ -z "$project_root" ]]; then
  project_root="$(find_root)"
fi
project_agents_dir="$project_root/.codex/agents"
if [[ "$project_agents_dir" != "$codex_agents_dir" ]]; then
  remove_generated_agents "$project_agents_dir"
fi

if command -v codex >/dev/null 2>&1; then
  mcp_get_file="$(mktemp "${TMPDIR:-/tmp}/claude-to-codex-mcp-get.XXXXXX")"
  if codex mcp get claude-bridge >"$mcp_get_file" 2>/dev/null; then
    if grep -q 'claude-to-codex' "$mcp_get_file"; then
      if [[ "$dry_run" -eq 1 ]]; then
        printf 'Would remove Codex MCP entry claude-bridge\n'
      else
        printf 'Removing Codex MCP entry claude-bridge\n'
      fi
      run codex mcp remove claude-bridge
    else
      printf 'Leaving Codex MCP entry claude-bridge because it does not appear to point at claude-to-codex\n'
    fi
  fi
else
  printf 'Codex CLI not found; leaving any Codex MCP config untouched\n'
fi

if [[ "$dry_run" -eq 1 ]]; then
  printf 'Dry run complete. No files were removed.\n'
else
  printf 'Uninstall complete. Claude Code configuration was not changed.\n'
fi
